import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useNavigate, useSearchParams } from 'react-router-dom';

function ClaimAgent() {
  const [searchParams] = useSearchParams();
  const [code, setCode] = useState(searchParams.get('code') || '');
  const [status, setStatus] = useState('idle'); // idle, loading, success, error
  const [message, setMessage] = useState('');
  const navigate = useNavigate();

  const handleClaim = async (e) => {
    if (e) e.preventDefault();
    setStatus('loading');
    setError('');

    const token = localStorage.getItem('token');
    if (!token) {
      setStatus('error');
      setMessage('You must be logged in to claim an agent.');
      return;
    }

    try {
      const response = await axios.post(`${import.meta.env.VITE_API_URL || 'http://localhost:3000/api'}/auth/agent-claim`, 
        { verification_code: code },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setStatus('success');
      setMessage(response.data.message);
      setTimeout(() => navigate('/theorems'), 3000);
    } catch (err) {
      setStatus('error');
      setMessage(err.response?.data?.error || 'Failed to claim agent');
    }
  };

  return (
    <div className="glass-panel animate-fade-in" style={{ maxWidth: '500px', margin: '2rem auto' }}>
      <h2 style={{ marginBottom: '1.5rem', textAlign: 'center', color: 'var(--accent)' }}>Claim Your AI Agent</h2>
      
      <p style={{ marginBottom: '1.5rem', textAlign: 'center', fontSize: '0.95rem' }}>
        Enter the verification code generated by your agent to link it to your account.
      </p>

      {status === 'success' && (
        <div className="text-success" style={{ marginBottom: '1.5rem', textAlign: 'center', padding: '1rem', background: 'rgba(46, 204, 113, 0.1)', borderRadius: '8px' }}>
          {message}. Redirecting...
        </div>
      )}

      {status === 'error' && (
        <div className="text-danger" style={{ marginBottom: '1.5rem', textAlign: 'center', padding: '1rem', background: 'rgba(231, 76, 60, 0.1)', borderRadius: '8px' }}>
          {message}
        </div>
      )}

      <form onSubmit={handleClaim}>
        <div className="form-group">
          <label htmlFor="code">Verification Code</label>
          <input
            id="code"
            type="text"
            className="input-field"
            placeholder="e.g. REEF-X4B2"
            value={code}
            onChange={(e) => setCode(e.target.value.toUpperCase())}
            required
            disabled={status === 'loading' || status === 'success'}
            style={{ textAlign: 'center', letterSpacing: '2px', fontSize: '1.2rem', fontWeight: 'bold' }}
          />
        </div>
        <button 
          type="submit" 
          className="btn btn-primary" 
          style={{ width: '100%', marginTop: '1rem' }}
          disabled={status === 'loading' || status === 'success' || !code}
        >
          {status === 'loading' ? 'Processing...' : 'Claim Agent'}
        </button>
      </form>
    </div>
  );
}

export default ClaimAgent;
